**Rupesh Dharme** <br>
**TE 01** <br>
**DSBDA Lab** <br>
**Assignment 03** <br>

#### Descriptive Statistics - Measures of Central Tendency and variability Perform the following operations on any open-source dataset (e.g., Iris.csv, nba.csv)


##### 1.	Provide summary statistics (mean, median, minimum, maximum, standard deviation) for a dataset (age, income etc.) with numeric variables grouped by one of the qualitative (categorical) variable. For example, if your categorical variable is age groups and quantitative variable is income, then provide summary statistics of income grouped by the age groups. Create a list that contains a numeric value for each response to the categorical variable.


In [1]:
# importing the required modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# reading the dataset
nba = pd.read_csv("nba.csv")
nba.head()

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0  
4                NaN  5000000.0

In [3]:
# describe method gives statistical summary of the data
nba.describe()

Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [4]:
nba.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [5]:
# show null values in the dataset
nba.iloc[457, :]

Name        NaN
Team        NaN
Number      NaN
Position    NaN
Age         NaN
Height      NaN
Weight      NaN
College     NaN
Salary      NaN
Name: 457, dtype: object

In [6]:
# drop 457 row 
nba = nba.drop(nba.index[457])
nba.isnull().sum()

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary      11
dtype: int64

In [7]:
nba["College"].fillna("No College", inplace=True)
nba["Salary"].fillna(nba["Salary"].mean(), inplace=True)
nba.isnull().sum()

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [8]:
# grouping nba dataset by Team
nba_grouped = nba.groupby('Team')
nba_grouped.head()

Name            Team  Number Position   Age Height  Weight  \
0     Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1       Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2      John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3       R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4     Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..              ...             ...     ...      ...   ...    ...     ...   
442   Trevor Booker       Utah Jazz    33.0       PF  28.0    6-8   228.0   
443      Trey Burke       Utah Jazz     3.0       PG  23.0    6-1   191.0   
444      Alec Burks       Utah Jazz    10.0       SG  24.0    6-6   214.0   
445      Dante Exum       Utah Jazz    11.0       PG  20.0    6-6   190.0   
446  Derrick Favors       Utah Jazz    15.0       PF  24.0   6-10   265.0   

               College        Salary  
0                Texas  7.730337e+06  
1            Marquette  6.796117e+06  
2    Boston University  4.842684e+06  
3        Georgia State  1.148640e+06  
4           No College  5.000000e+06  
..                 ...           ...  
442            Clemson  4.775000e+06  
443           Michigan  2.658240e+06  
444           Colorado  9.463484e+06  
445         No College  3.777720e+06  
446       Georgia Tech  1.200000e+07  

[150 rows x 9 columns]

In [9]:
# describing the statistics of Salary of the grouped data by Team
nba_grouped["Salary"].describe()

count          mean           std        min  \
Team                                                                   
Atlanta Hawks            15.0  4.860197e+06  5.194508e+06   525093.0   
Boston Celtics           15.0  4.225583e+06  3.036396e+06  1148640.0   
Brooklyn Nets            15.0  3.501898e+06  5.317817e+06   134215.0   
Charlotte Hornets        15.0  5.222728e+06  4.538601e+06   189455.0   
Chicago Bulls            15.0  5.785559e+06  6.251088e+06   525093.0   
Cleveland Cavaliers      15.0  7.455425e+06  7.484116e+06   111196.0   
Dallas Mavericks         15.0  4.746582e+06  5.030279e+06   525093.0   
Denver Nuggets           15.0  4.330974e+06  4.165468e+06   258489.0   
Detroit Pistons          15.0  4.477884e+06  4.668478e+06   111444.0   
Golden State Warriors    15.0  5.924600e+06  5.664282e+06   289755.0   
Houston Rockets          15.0  5.018868e+06  6.414749e+06   200600.0   
Indiana Pacers           15.0  4.450122e+06  4.584514e+06   211744.0   
Los Angeles Clippers     15.0  6.323643e+06  7.600225e+06   111444.0   
Los Angeles Lakers       15.0  4.784695e+06  6.835688e+06   525093.0   
Memphis Grizzlies        18.0  5.328979e+06  4.556591e+06   700902.0   
Miami Heat               15.0  6.146736e+06  7.285680e+06   261894.0   
Milwaukee Bucks          16.0  4.350220e+06  4.875071e+06   295327.0   
Minnesota Timberwolves   14.0  4.610884e+06  3.977783e+06   947276.0   
New Orleans Pelicans     19.0  4.355304e+06  4.537874e+06    55722.0   
New York Knicks          16.0  4.581494e+06  5.952487e+06    30888.0   
Oklahoma City Thunder    15.0  6.251020e+06  6.632400e+06   222888.0   
Orlando Magic            14.0  4.297248e+06  3.068412e+06   845059.0   
Philadelphia 76ers       15.0  2.389039e+06  1.953024e+06   525093.0   
Phoenix Suns             15.0  4.229676e+06  5.022561e+06    55722.0   
Portland Trail Blazers   15.0  3.220121e+06  2.392741e+06   525093.0   
Sacramento Kings         15.0  4.778911e+06  4.701792e+06   525093.0   
San Antonio Spurs        15.0  5.629516e+06  6.396804e+06   200600.0   
Toronto Raptors          15.0  4.741174e+06  4.195943e+06   245177.0   
Utah Jazz                15.0  4.204006e+06  4.467878e+06   900000.0   
Washington Wizards       15.0  5.088576e+06  4.869388e+06   200600.0   

                               25%           50%           75%         max  
Team                                                                        
Atlanta Hawks           1152260.00  2.854940e+06  6.873240e+06  18671659.0  
Boston Celtics          1994760.00  3.425510e+06  5.898058e+06  12000000.0  
Brooklyn Nets            947276.00  1.335480e+06  2.512675e+06  19689000.0  
Charlotte Hornets       1543138.00  4.204200e+06  6.665702e+06  13500000.0  
Chicago Bulls           1203290.50  2.380440e+06  7.974380e+06  20093064.0  
Cleveland Cavaliers     1211638.00  4.950000e+06  1.162482e+07  22970500.0  
Dallas Mavericks        1185783.00  3.950313e+06  5.289487e+06  16407500.0  
Denver Nuggets          1647099.50  3.000000e+06  4.593842e+06  14000000.0  
Detroit Pistons         1711452.50  2.891760e+06  5.635000e+06  16000000.0  
Golden State Warriors   1201462.00  3.815000e+06  1.154062e+07  15501000.0  
Houston Rockets          973638.00  2.288205e+06  7.339758e+06  22359364.0  
Indiana Pacers          1053513.00  4.000000e+06  5.697112e+06  17120106.0  
Los Angeles Clippers    1024164.00  3.110796e+06  8.367500e+06  21468695.0  
Los Angeles Lakers       896167.50  1.724250e+06  5.161144e+06  25000000.0  
Memphis Grizzlies       1939075.00  4.842684e+06  5.387635e+06  19688000.0  
Miami Heat               947276.00  2.854940e+06  7.847668e+06  22192730.0  
Milwaukee Bucks         1483589.00  2.254167e+06  5.514330e+06  16407500.0  
Minnesota Timberwolves  1590540.00  3.049180e+06  5.744910e+06  12700000.0  
New Orleans Pelicans     981348.50  2.850000e+06  7.785365e+06  15514031.0  
New York Knicks          921721.75  2.225421e+06  4.949493e+06  22875000.0  
Oklahoma City Thunder   1

Observation

It is observed that:

- The mean salary of players playing in Atalanta Hawks is higher than the other two. 

- However, the maximum salary is offered by Brooklyn Nets.

- The large standard deviation of Salaries in Atalanta Hawks indicates that their is a disparity in player salaries between the players at the same team.

- The players who play in the Center (C) have the highest mean salary.

- The maximum salary is paid to Small Forward (SF).

- Interestingly, the lowest salary is also paid to a Small Forward ($31,000).

- The mean age of players in each position is almost similar (27 years).

The Maximum age of players in NBA is:  40.0
The Minimum age of players in NBA is:  19.0

- Players in the Age Group 30-39 have the maximum mean salary, probably because they are already famous and in their prime.

- Players in the Age Group 10-19 are given less salary, because they are yet to be of proven quality.

##### 2.	Write a Python program to display some basic statistical details like percentile, mean, standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris- versicolor’ of iris.csv dataset. Provide the codes with outputs and explain everything that you do in this step.


In [10]:
# importing iris dataset
iris = pd.read_csv("Iris.csv")
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [11]:
# overall statistics of the dataset
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [12]:
# no null values in the dataset
iris.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [13]:
# grouping data by Species
iris_grouped = iris.groupby('Species')
iris_grouped.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
50    51            7.0           3.2            4.7           1.4   
51    52            6.4           3.2            4.5           1.5   
52    53            6.9           3.1            4.9           1.5   
53    54            5.5           2.3            4.0           1.3   
54    55            6.5           2.8            4.6           1.5   
100  101            6.3           3.3            6.0           2.5   
101  102            5.8           2.7            5.1           1.9   
102  103            7.1           3.0            5.9           2.1   
103  104            6.3           2.9            5.6           1.8   
104  105            6.5           3.0            5.8           2.2   

             Species  
0        Iris-setosa  
1        Iris-setosa  
2        Iris-setosa  
3        Iris-setosa  
4        Iris-setosa  
50   Iris-versicolor  
51   Iris-versicolor  
52   Iris-versicolor  
53   Iris-versicolor  
54   Iris-versicolor  
100   Iris-virginica  
101   Iris-virginica  
102   Iris-virginica  
103   Iris-virginica  
104   Iris-virginica

In [25]:
# describing the statistics of the grouped data by Species
iris_grouped[["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]].describe()

SepalLengthCm                                              \
                        count   mean       std  min    25%  50%  75%  max   
Species                                                                     
Iris-setosa              50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8   
Iris-versicolor          50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0   
Iris-virginica           50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9   

                SepalWidthCm         ... PetalLengthCm      PetalWidthCm  \
                       count   mean  ...           75%  max        count   
Species                              ...                                   
Iris-setosa             50.0  3.418  ...         1.575  1.9         50.0   
Iris-versicolor         50.0  2.770  ...         4.600  5.1         50.0   
Iris-virginica          50.0  2.974  ...         5.875  6.9         50.0   

                                                           
                  mean       std  min  25%  50%  75%  max  
Species                                                    
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6  
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8  
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5  

[3 rows x 32 columns]

### Observations 
Avg values of Iris-setosa is more only in sepalwidth in comparison to other varities,
Although Avg sepalLW of versicolor > virginica, the avg petalLW of versicolor < virginica,

based on standard deviation, setosa has lesser value than others in sepal length, petal width, petal length meaning most of them are near mean length

similarly: versicolor for sepal width samples taken for virginica have most variation in the measured characteristics